# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Json2struct < Formula
  desc ""
  homepage ""
  version "1.9.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marhaupe/json2struct/releases/download/v1.9.0/json2struct_Darwin_x86_64.tar.gz"
      sha256 "49b7942d899b12a937eccf8eefd75e537242cd77b62c3ea9440cb1b90a3a3910"

      def install
        bin.install "json2struct"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marhaupe/json2struct/releases/download/v1.9.0/json2struct_Darwin_arm64.tar.gz"
      sha256 "ffab3e21e237b91a7bf554e2f0862f01de49b3f7dc88ca2f116ac3839772ab63"

      def install
        bin.install "json2struct"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marhaupe/json2struct/releases/download/v1.9.0/json2struct_Linux_x86_64.tar.gz"
        sha256 "1c43bf5f0f946c7c56744b6e7e1e9552defe01d776ac6afe9dad92cee9ad0d84"

        def install
          bin.install "json2struct"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marhaupe/json2struct/releases/download/v1.9.0/json2struct_Linux_arm64.tar.gz"
        sha256 "a3bb44fb60469635d041ed0f92f4ec14992a57f193049a4dbbac05f079743dc5"

        def install
          bin.install "json2struct"
        end
      end
    end
  end
end
