# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Json2struct < Formula
  desc ""
  homepage ""
  version "1.4.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/marhaupe/json2struct/releases/download/v1.4.1/json2struct_1.4.1_macOS_arm64.tar.gz"
      sha256 "47bc7f3061d8821c2dec7c0542ba2ec95c68e7fb91fad77223e776b0c1bf1a57"

      def install
        bin.install "json2struct"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/marhaupe/json2struct/releases/download/v1.4.1/json2struct_1.4.1_macOS_64-bit.tar.gz"
      sha256 "3e0862d5ffe53cce5f85f1edf36208c4fc9e8c71d8cfa89ce0b57ab3d31470b3"

      def install
        bin.install "json2struct"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marhaupe/json2struct/releases/download/v1.4.1/json2struct_1.4.1_linux_arm64.tar.gz"
      sha256 "aef61fa25f65792f33f47a55b4a5dca76aeea3c1e120aea74d83d610cd4b4fca"

      def install
        bin.install "json2struct"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/marhaupe/json2struct/releases/download/v1.4.1/json2struct_1.4.1_linux_64-bit.tar.gz"
      sha256 "3c4afd209dba67c4777c77aa8ffff2667e0d4175dfa131883b86af676f50defa"

      def install
        bin.install "json2struct"
      end
    end
  end

  depends_on "git"
end
