# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Json2struct < Formula
  desc ""
  homepage ""
  version "1.9.1"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marhaupe/json2struct/releases/download/v1.9.1/json2struct_Darwin_x86_64.tar.gz"
      sha256 "57a8161d7cf0e6cf35f5c1ab1066a1f066e2a3f56bbfc301234be8b3057c7963"

      def install
        bin.install "json2struct"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marhaupe/json2struct/releases/download/v1.9.1/json2struct_Darwin_arm64.tar.gz"
      sha256 "a4f77b8ee02aeb7d207fb7aaf882b26a7df0838ce74f016f1369f3cddffd575f"

      def install
        bin.install "json2struct"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marhaupe/json2struct/releases/download/v1.9.1/json2struct_Linux_x86_64.tar.gz"
        sha256 "5b8947e4b47542b6190e159b43cf063fdb370f2f5e8cd8a59eabde7f3ffef0af"

        def install
          bin.install "json2struct"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marhaupe/json2struct/releases/download/v1.9.1/json2struct_Linux_arm64.tar.gz"
        sha256 "1fb1fb3913d53609f0ad3f1c4d3350edf46f1aba8d6d57b7181ef07c4efd35d9"

        def install
          bin.install "json2struct"
        end
      end
    end
  end
end
