# This file was generated by GoReleaser. DO NOT EDIT.
class Json2struct < Formula
  desc ""
  homepage ""
  version "1.3.0-beta.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/marhaupe/json2struct/releases/download/v1.3.0-beta.5/json2struct_1.3.0-beta.5_macOS_64-bit.tar.gz"
    sha256 "7078bf36341092e347f20c3b5445cfe99b7ac61962248c3e9c088d49e5544ea7"
  elsif OS.linux?
    url "https://github.com/marhaupe/json2struct/releases/download/v1.3.0-beta.5/json2struct_1.3.0-beta.5_linux_64-bit.tar.gz"
    sha256 "6ac2ab055daaeb92cb35e7ad2c70097364b0857505800dcd80cc077d106f1d61"
  end
  
  depends_on "git"

  def install
    bin.install "json2struct"
  end
end
